spring:
  application:
    name: config-server  cloud:    config:      server:        git:          uri: https://github.com/dengjinhmm/springCloudConfig
          search-paths:          - respo
      label: master            
server:  port: 8888
  
  #defaultZone: http://localhost:8761/eureka/

eureka:  client:    service-url:      defaultZone: http://localhost:8889/eureka/

                